import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:local_auth/local_auth.dart';
import 'package:random_password_generator/random_password_generator.dart';

import '../../../generated/l10n.dart';
import '../../cubits/cubits.dart';
import '../../models/models.dart';
import '../../utils/loggers/ouisync_app_logger.dart';
import '../../utils/utils.dart';
import '../widgets.dart';

class RepositoryCreation extends StatefulWidget {
  RepositoryCreation(
      {Key? key,
      required this.context,
      required this.cubit,
      required this.formKey})
      : super(key: key);

  final BuildContext context;
  final ReposCubit cubit;
  final GlobalKey<FormState> formKey;

  @override
  State<RepositoryCreation> createState() => _RepositoryCreationState();
}

class _RepositoryCreationState extends State<RepositoryCreation>
    with OuiSyncAppLogger {
  final TextEditingController _nameController =
      TextEditingController(text: null);

  final TextEditingController _passwordController =
      TextEditingController(text: null);

  final TextEditingController _retypedPasswordController =
      TextEditingController(text: null);

  bool _obscurePassword = true;
  bool _obscurePasswordConfirm = true;

  bool _biometricsAvailable = false;
  bool _useBiometrics = false;

  bool _generatePassword = true;

  bool _showPasswordSection = true;
  bool _showRetypePassword = true;

  @override
  void initState() {
    super.initState();

    isBiometricsAvailable().then((isAvailable) {
      setState(() {
        _biometricsAvailable = isAvailable ?? false;
        _useBiometrics = isAvailable ?? false;
      });

      _configureInputs(_generatePassword, _useBiometrics);

      if (isAvailable == null) return; //Device without biometrics

      if (isAvailable == false) {
        // Show dialog asking the user to enable biometrics
        return;
      }
    });
  }

  Future<bool?> isBiometricsAvailable() async {
    final auth = LocalAuthentication();

    final isBiometricsAvaiable = await auth.canCheckBiometrics;
    if (!isBiometricsAvaiable) {
      return null; //The device doesn't have biometrics
    }

    final availableBiometrics = await auth.getAvailableBiometrics();
    if (availableBiometrics.isEmpty) {
      return false; //The device has biometrics, but the user hasn't configured them
    }

    return true;
  }

  String _generateRandomPassword() {
    final password = RandomPasswordGenerator();
    final autogeneratedPassword = password.randomPassword(
        letters: true,
        numbers: true,
        specialChar: true,
        uppercase: true,
        passwordLength: 24);

    if (kDebugMode) {
      loggy.app(
          'Autogenerated password for repo ${_nameController.text}: $autogeneratedPassword');
    }

    return autogeneratedPassword;
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: widget.formKey,
      autovalidateMode: AutovalidateMode.onUserInteraction,
      child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            SingleChildScrollView(
                reverse: true,
                child: _buildCreateRepositoryWidget(widget.context))
          ]),
    );
  }

  Widget _buildCreateRepositoryWidget(BuildContext context) {
    return Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Dimensions.spacingVerticalDouble,
          _repoName(),
          _passwordInputs(),
          _generatePasswordCheckbox(),
          if (_biometricsAvailable) _useBiometricsCheckbox(),
          _manualPasswordWarning(),
          Fields.dialogActions(context, buttons: _actions(context)),
        ]);
  }

  Widget _repoName() {
    return Fields.formTextField(
        context: context,
        textEditingController: _nameController,
        label: S.current.labelName,
        hint: S.current.messageRepositoryName,
        onSaved: (_) {},
        validator:
            validateNoEmpty(S.current.messageErrorFormValidatorNameDefault),
        autofocus: true,
        autovalidateMode: AutovalidateMode.disabled);
  }

  Widget _passwordInputs() => Visibility(
      visible: _showPasswordSection,
      child: Container(
          child: Column(
        children: [
          Row(children: [
            Expanded(
                child: Fields.formTextField(
                    context: context,
                    textEditingController: _passwordController,
                    obscureText: _obscurePassword,
                    label: S.current.labelPassword,
                    subffixIcon: Fields.actionIcon(
                        Icon(
                          _obscurePassword
                              ? Constants.iconVisibilityOn
                              : Constants.iconVisibilityOff,
                          size: Dimensions.sizeIconSmall,
                        ), onPressed: () {
                      setState(() => _obscurePassword = !_obscurePassword);
                    }),
                    hint: S.current.messageRepositoryPassword,
                    onSaved: (_) {},
                    validator: validateNoEmpty(
                        Strings.messageErrorRepositoryPasswordValidation),
                    autovalidateMode: AutovalidateMode.disabled))
          ]),
          Visibility(
              visible: _showRetypePassword,
              child: Row(children: [
                Expanded(
                  child: Fields.formTextField(
                      context: context,
                      textEditingController: _retypedPasswordController,
                      obscureText: _obscurePasswordConfirm,
                      label: S.current.labelRetypePassword,
                      subffixIcon: Fields.actionIcon(
                          Icon(
                            _obscurePasswordConfirm
                                ? Constants.iconVisibilityOn
                                : Constants.iconVisibilityOff,
                            size: Dimensions.sizeIconSmall,
                          ), onPressed: () {
                        setState(() =>
                            _obscurePasswordConfirm = !_obscurePasswordConfirm);
                      }),
                      hint: S.current.messageRepositoryPassword,
                      onSaved: (_) {},
                      validator: (retypedPassword) => retypedPasswordValidator(
                            password: _passwordController.text,
                            retypedPassword: retypedPassword,
                          ),
                      autovalidateMode: AutovalidateMode.disabled),
                )
              ])),
        ],
      )));

  Widget _generatePasswordCheckbox() => Container(
      child: SwitchListTile.adaptive(
          value: _generatePassword,
          title: Text('Generate password', textAlign: TextAlign.end),
          onChanged: (generatePassword) {
            setState(() => _generatePassword = generatePassword);

            _configureInputs(_generatePassword, _useBiometrics);
          },
          contentPadding: EdgeInsets.zero));

  Widget _useBiometricsCheckbox() => Container(
      child: SwitchListTile.adaptive(
          value: _useBiometrics,
          title: Text('Secure using biometrics', textAlign: TextAlign.end),
          onChanged: (enableBiometrics) {
            setState(() => _useBiometrics = enableBiometrics);

            _configureInputs(_generatePassword, _useBiometrics);
          },
          contentPadding: EdgeInsets.zero));

  _configureInputs(bool generatePassword, bool useBiometrics) {
    final showPasswordSection = !(_generatePassword && _useBiometrics);
    final showRetypePassword = !(_generatePassword && !_useBiometrics);

    setState(() {
      _showPasswordSection = showPasswordSection;
      _showRetypePassword = showRetypePassword;
    });

    final password = _generatePassword ? _generateRandomPassword() : '';

    _passwordController.text = password;
    _retypedPasswordController.text = password;
  }

  Widget _manualPasswordWarning() => Padding(
      padding: Dimensions.paddingVertical10,
      child: Visibility(
          visible: !_useBiometrics,
          child: Fields.autosizeText(
              'Remember to securely save the password.\n\nIf you forget it, there is no way to retrieve it.',
              color: Colors.red,
              maxLines: 10,
              softWrap: true,
              textOverflow: TextOverflow.ellipsis)));

  String? retypedPasswordValidator({
    required String password,
    required String? retypedPassword,
  }) {
    if (retypedPassword == null || password != retypedPassword) {
      return S.current.messageErrorRetypePassword;
    }

    return null;
  }

  List<Widget> _actions(context) => [
        NegativeButton(
            text: S.current.actionCancel,
            onPressed: () => Navigator.of(context).pop('')),
        PositiveButton(
            text: S.current.actionCreate,
            onPressed: () {
              final name = _nameController.text;
              final password = _passwordController.text;

              _createRepo(name: name, password: password);
            })
      ];

  void _createRepo({required String name, required String password}) =>
      _onSaved(widget.cubit, name, password);

  void _onSaved(ReposCubit cubit, String name, String password) async {
    if (!(widget.formKey.currentState?.validate() ?? false)) {
      return;
    }

    widget.formKey.currentState!.save();

    if (_useBiometrics) {
      await Biometrics.addRepositoryPassword(
          repositoryName: name, password: password);
    }

    final info = RepoMetaInfo.fromDirAndName(
        await cubit.settings.defaultRepoLocation(), name);

    final repoEntry = await cubit.createRepository(
      info,
      password: password,
      setCurrent: true,
    );

    if (repoEntry is ErrorRepoEntry) {
      Dialogs.simpleAlertDialog(
        context: widget.context,
        title: S.current.messsageFailedCreateRepository(name),
        message: repoEntry.error,
      );

      Biometrics.deleteRepositoryPassword(repositoryName: name);
      return;
    }

    Navigator.of(widget.context).pop(name);
  }
}
